- name: Check if a reboot is needed on all server
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Install essential packages  
  package:
          name: "{{ packages }}"
          state: latest

- name: Disable SSH password authentication
  lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp: "^#PasswordAuthentication yes"
          line: "PasswordAuthentication no"
  notify: "Restart sshd"

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
          path: /etc/sudoers
          state: present
          regexp: "^%wheel"
          line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
          validate: "visudo -cf %s"

- name: Restart SSH daemon
  service:
          name: sshd
          state: restarted

- name: Update packages (Debian-based)
  apt: 
          update_cache: yes 
          force_apt_get: yes
          cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade all packages on servers
  apt:
          upgrade: dist
          force_apt_get: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Reboot the box if kernel updated
  reboot:
          msg: "Reboot initiated for kernal updates"
          connect_timeout: 5
          reboot_timeout: 300
          pre_reboot_delay: 0
          post_reboot_delay: 30
          test_command: uptime
  when: ansible_facts['os_family'] == "Debian" and reboot_required_file.stat.exists
